site_name: PyGitAI
repo_url: https://github.com/JangasCodingplace/pygitai
edit_uri: https://github.com/JangasCodingplace/pygitai/blob/main/docs/

nav:
  - Introduction: index.md
  - User Guides:
    - Add Custom LLM: user_guides/add_custom_llm.md
  - API:
    - PromptLine: api/PromptLine.md
    - ParserBase: api/ParserBase.md
    - LLMBase: api/LLMBase.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md
  - License: LICENSE

theme: 
  name: readthedocs

plugins:
  - search
  - mkdocstrings
