site_name: PyGitAI
repo_url: https://github.com/JangasCodingplace/pygitai
edit_uri: https://github.com/JangasCodingplace/pygitai/blob/main/docs/

nav:
  - Introduction: index.md
  - Get Started:
    - CLI Commands: usage/cli-commands.md
  - User Guides:
    - Add Custom LLM: user-guides/add-custom-llm.md
    - Overwrite Template Files: user-guides/overwrite-template-files.md
    - Add Custom Jobs: user-guides/add-custom-jobs.md
  - Presets:
    - (Job) AutoStageAll: presets/JobAutoStageAll.md
    - (Job) PreCommitHook: presets/JobPreCommitHook.md
    - (LLM Job) CommitBody: presets/JobCommitBody.md
    - (LLM Job) CommitTitle: presets/JobCommitTitle.md
    - (LLM Job) FeedbackOnCommit: presets/JobFeedbackOnCommit.md
    - (LLM Job) CodeReview: presets/JobCodeReview.md
  - API:
    - PromptLine: api/PromptLine.md
    - ParserBase: api/ParserBase.md
    - JobBase: api/JobBase.md
    - LLMBase: api/LLMBase.md
    - LLMJobBase: api/LLMJobBase.md
  - Contributing: CONTRIBUTING.md
  - Changelog: CHANGELOG.md
  - License: LICENSE

theme: 
  name: readthedocs

plugins:
  - search
  - mkdocstrings
